name: CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Build with Maven
      run: |
        cd MarkdownConverter
        mvn -B package


    - name: Run tests
      run: |
        cd MarkdownConverter
        mvn -B test
